// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdWTFtjpGRCHUxj0ISYhGBlvMnC7XivFM',
    appId: '1:677056697761:web:49179423f1c3329b6767e0',
    messagingSenderId: '677056697761',
    projectId: 'diet-tracker10',
    authDomain: 'diet-tracker10.firebaseapp.com',
    databaseURL: 'https://diet-tracker10-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'diet-tracker10.appspot.com',
    measurementId: 'G-03EL0B1F0L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6Z2sAUkkdf6zV-FuVmb_kc7_cY7g3-hQ',
    appId: '1:677056697761:android:df1484750c70e1226767e0',
    messagingSenderId: '677056697761',
    projectId: 'diet-tracker10',
    databaseURL: 'https://diet-tracker10-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'diet-tracker10.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1DKcVaUdkR4xu23zIpzg-OfufCV4pbh8',
    appId: '1:677056697761:ios:36fce9a8d40ba44f6767e0',
    messagingSenderId: '677056697761',
    projectId: 'diet-tracker10',
    databaseURL: 'https://diet-tracker10-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'diet-tracker10.appspot.com',
    iosBundleId: 'com.example.beslenme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1DKcVaUdkR4xu23zIpzg-OfufCV4pbh8',
    appId: '1:677056697761:ios:5576cae979990ce96767e0',
    messagingSenderId: '677056697761',
    projectId: 'diet-tracker10',
    databaseURL: 'https://diet-tracker10-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'diet-tracker10.appspot.com',
    iosBundleId: 'com.example.beslenme.RunnerTests',
  );
}
